config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/jinluchang/Qlattice:
      branch: master
      repo: https://github.com/jinluchang/Qlattice
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/jinluchang/Qlattice git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-dandelion-moorhen.sh
        container: qc.acc_sleepy-charcoal-gharial
  QC.Doc:
    repos:
      github.com/jinluchang/Qlattice find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-seashell-flounder.sh
        container: qc.doc_craggy-goldenrod-tetra
      github.com/jinluchang/Qlattice git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-cerulean-mayfly.sh
        container: qc.doc_flaky-linen-cuttlefish
      github.com/jinluchang/Qlattice markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-periwinkle-fox.sh
        container: qc.doc_bumpy-puce-lobster
      github.com/jinluchang/Qlattice restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-firebrick-javanese.sh
        container: qc.doc_whiny-ecru-kiwi
  QC.Lic:
    repos:
      github.com/jinluchang/Qlattice licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-indigo-paradise.sh
        container: qc.lic_foggy-ruby-dunker
  QC.Sec:
    repos:
      github.com/jinluchang/Qlattice bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-viridian-jaguar.sh
        container: qc.sec_chewy-magnolia-shark
  QC.Sty:
    repos:
      github.com/jinluchang/Qlattice flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-ruby-deer.sh
        container: qc.sty_cloudy-goldenrod-millipede
      github.com/jinluchang/Qlattice jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-sapphire-affenpinscher.sh
        container: qc.sty_baggy-eggplant-urchin
      github.com/jinluchang/Qlattice oclint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-aqua-warthog.sh
        container: qc.sty_queasy-charcoal-bandicoot
  QC.Uni:
    repos:
      github.com/jinluchang/Qlattice pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-linen-giraffe.sh
        container: qc.uni_gamy-eggplant-buffalo
  QC.Ver:
    repos:
      github.com/jinluchang/Qlattice get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-ochre-frigatebird.sh
        container: qc.ver_snoopy-eggplant-mastiff
timeout: 5400
